
#  NUMPY

In [1]:
import numpy as np


In [2]:
my_list=[1,2,3,4,5,6,7]
arr=np.array(my_list)

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
arr2=np.array([[1,2,3,4],[1,3,4,5]])
arr2

array([[1, 2, 3, 4],
       [1, 3, 4, 5]])

In [6]:
arr2.ndim

2

In [7]:
arr.ndim

1

In [8]:
arr2.shape

(2, 4)

In [9]:
arr.shape

(7,)

In [10]:
np.__version__

'1.25.2'

In [12]:
arr3=np.array([[[1,2,3],[1,2,4]],[[1,2,3],[1,2,4]]])
arr3

array([[[1, 2, 3],
        [1, 2, 4]],

       [[1, 2, 3],
        [1, 2, 4]]])

In [13]:
arr3.ndim

3

In [14]:
arr[1]

2

In [15]:
arr
arr2
arr3

array([[[1, 2, 3],
        [1, 2, 4]],

       [[1, 2, 3],
        [1, 2, 4]]])

In [16]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
arr2

array([[1, 2, 3, 4],
       [1, 3, 4, 5]])

In [18]:
arr3

array([[[1, 2, 3],
        [1, 2, 4]],

       [[1, 2, 3],
        [1, 2, 4]]])

In [20]:
arr[1]+arr2[1][2]

6

In [22]:
arr3[1,0,2]

3

In [23]:
arr3[1,1,2]

4

In [25]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
b=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])
b

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [27]:
c=np.array([[[1,2,3],[1,3,4]],[[2,3,4],[4,5,6]]])
c

array([[[1, 2, 3],
        [1, 3, 4]],

       [[2, 3, 4],
        [4, 5, 6]]])

In [30]:
b=np.linspace(0,6,8)
b

array([0.        , 0.85714286, 1.71428571, 2.57142857, 3.42857143,
       4.28571429, 5.14285714, 6.        ])

In [47]:
c=np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
arr2.sum(axis=1)

array([10, 13])

In [49]:
arr2.argmax()

7

In [50]:
arr2.argmin()

0

In [36]:
# slicing



a=np.arange(4)
a

array([0, 1, 2, 3])

In [37]:
a[:3]

array([0, 1, 2])

In [38]:
a[1:2]

array([1])

In [39]:
a[::-1]

array([3, 2, 1, 0])

In [40]:
a[2:-1]

array([2])

In [41]:
a[::-2]

array([3, 1])

In [43]:
# random values


r=np.random.rand(7)
r

array([0.16206512, 0.82038744, 0.03476907, 0.21041146, 0.24235348,
       0.31397984, 0.60184337])

In [45]:
r1=np.random.rand(7)
r1

array([0.93433556, 0.53830359, 0.84044308, 0.36476787, 0.51694792,
       0.48205557, 0.29608075])

In [46]:
r2=np.random.rand(7)
r2

array([0.63576537, 0.87029048, 0.45959875, 0.15784422, 0.93361388,
       0.00497759, 0.13879407])

In [56]:
data=np.random.randint(1,2000,(100,4))
data

array([[ 299,  117, 1905, 1189],
       [ 645, 1244, 1067, 1781],
       [  23,  500,  696, 1728],
       [1071,  261,  856, 1625],
       [1027,  142, 1999, 1411],
       [1787, 1565, 1675, 1928],
       [1555, 1620, 1885,  200],
       [1112,  996, 1673, 1460],
       [1361,  201,  686, 1808],
       [ 598, 1761,  434,  274],
       [1786, 1987,   29, 1118],
       [ 678,  577,  386,  559],
       [1188, 1043, 1301, 1877],
       [ 485,  198, 1633, 1040],
       [  83, 1508,  369,  329],
       [1650, 1256, 1396,  776],
       [1648,  158, 1959, 1164],
       [1395, 1916,  912, 1963],
       [1331, 1457, 1253,  179],
       [ 370,  867,  134,   44],
       [ 821, 1323,  623,  369],
       [1722, 1133,  122,    4],
       [1510,   34, 1042,  929],
       [1070, 1046, 1283, 1244],
       [  37, 1189,  901,  321],
       [ 487, 1808,  718, 1375],
       [1835, 1580,  254,  604],
       [1095,  945, 1803, 1176],
       [1232, 1785,  588,  809],
       [ 361, 1487,  586,  725],
       [ 1

In [59]:
z=data[:80,::-2]

In [60]:
z

array([[1189,  117],
       [1781, 1244],
       [1728,  500],
       [1625,  261],
       [1411,  142],
       [1928, 1565],
       [ 200, 1620],
       [1460,  996],
       [1808,  201],
       [ 274, 1761],
       [1118, 1987],
       [ 559,  577],
       [1877, 1043],
       [1040,  198],
       [ 329, 1508],
       [ 776, 1256],
       [1164,  158],
       [1963, 1916],
       [ 179, 1457],
       [  44,  867],
       [ 369, 1323],
       [   4, 1133],
       [ 929,   34],
       [1244, 1046],
       [ 321, 1189],
       [1375, 1808],
       [ 604, 1580],
       [1176,  945],
       [ 809, 1785],
       [ 725, 1487],
       [1087,  633],
       [1268, 1628],
       [1496,  896],
       [1471,  920],
       [ 754,  537],
       [1368,  557],
       [1598, 1110],
       [ 968, 1559],
       [ 390,  610],
       [ 250,   68],
       [ 154, 1523],
       [1828, 1572],
       [1943,   32],
       [1530,  223],
       [1716, 1789],
       [1674,  125],
       [ 697, 1705],
       [1119,

In [64]:
s=range(1000)
s 

%timeit [i//2 for i in s]

56.7 µs ± 2.53 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [65]:
p=np.arange(1000)
%timeit p//2

1.92 µs ± 253 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
