In [1]:
 import numpy as np

In [2]:
myls=[1,2,3,4,5]
type(myls)

list

In [3]:
arr=np.array(myls)
type(arr)

numpy.ndarray

In [4]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
a.ndim

2

In [6]:
a.shape

(2, 4)

In [7]:
b=np.array([[1,2,3,4],[5,6,7,8],[11,22,33,44]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 22, 33, 44]])

In [8]:
b.ndim

2

In [9]:
b.shape

(3, 4)

In [10]:
y=np.zeros((3,4))
y

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
a=np.linspace(0,1,6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [12]:
b=np.random.rand(4)
b

array([0.20875078, 0.18394131, 0.72669535, 0.57107277])

In [13]:
c=np.random.rand(4)
c

array([0.34666505, 0.25483643, 0.09428128, 0.0079569 ])

In [14]:
u=np.random.rand(4)
u

array([0.09508197, 0.37302118, 0.08108348, 0.78669262])

In [15]:
import numpy as np
import pandas as pd
from numpy.random import randn

In [17]:
df=pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
df

W         X         Y         Z
A -0.005986  0.319828 -0.163077 -0.727144
B  0.959484  0.574511  0.925415  1.068290
C  1.378405 -0.920963 -0.030847  2.019817
D -1.667353 -0.181667 -1.251846  0.389081
E -0.177269  1.223969 -0.054512 -0.223493

In [18]:
df

W         X         Y         Z
A -0.005986  0.319828 -0.163077 -0.727144
B  0.959484  0.574511  0.925415  1.068290
C  1.378405 -0.920963 -0.030847  2.019817
D -1.667353 -0.181667 -1.251846  0.389081
E -0.177269  1.223969 -0.054512 -0.223493

In [19]:
df['W']

A   -0.005986
B    0.959484
C    1.378405
D   -1.667353
E   -0.177269
Name: W, dtype: float64

In [20]:
type(df['W'])

pandas.core.series.Series

In [21]:
type(df)

pandas.core.frame.DataFrame

In [23]:
df[['W','Z']]

W         Z
A -0.005986 -0.727144
B  0.959484  1.068290
C  1.378405  2.019817
D -1.667353  0.389081
E -0.177269 -0.223493

In [25]:
df['NEW']=df['W']+df['Y']
df

W         X         Y         Z       NEW
A -0.005986  0.319828 -0.163077 -0.727144 -0.169063
B  0.959484  0.574511  0.925415  1.068290  1.884900
C  1.378405 -0.920963 -0.030847  2.019817  1.347559
D -1.667353 -0.181667 -1.251846  0.389081 -2.919198
E -0.177269  1.223969 -0.054512 -0.223493 -0.231781

In [26]:
df.drop('NEW',axis=1)
df

W         X         Y         Z       NEW
A -0.005986  0.319828 -0.163077 -0.727144 -0.169063
B  0.959484  0.574511  0.925415  1.068290  1.884900
C  1.378405 -0.920963 -0.030847  2.019817  1.347559
D -1.667353 -0.181667 -1.251846  0.389081 -2.919198
E -0.177269  1.223969 -0.054512 -0.223493 -0.231781

In [27]:
df.drop('NEW',axis=1,inplace=True)

In [28]:
df

W         X         Y         Z
A -0.005986  0.319828 -0.163077 -0.727144
B  0.959484  0.574511  0.925415  1.068290
C  1.378405 -0.920963 -0.030847  2.019817
D -1.667353 -0.181667 -1.251846  0.389081
E -0.177269  1.223969 -0.054512 -0.223493

In [30]:
import pandas as pd
import numpy as np

In [31]:
d={'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}
d

{'A': [1, 2, nan], 'B': [5, nan, nan], 'C': [1, 2, 3]}

In [32]:
df=pd.DataFrame(d)
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [33]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [34]:
df.dropna(axis=1)#Axis=1 is working on columns 
#axis=0 is working on rows

C
0  1
1  2
2  3

In [35]:
data={'company':['goog','goog','fb','fb','tw','tw'],'person':['sam','mic','jack','rack','mac','mc'],'sales':[200,300,150,450,550,650]}
df2=pd.DataFrame(data)
df2

company person  sales
0    goog    sam    200
1    goog    mic    300
2      fb   jack    150
3      fb   rack    450
4      tw    mac    550
5      tw     mc    650

In [38]:
bycomp=df2.groupby('company')

In [39]:
bycomp.mean()

TypeError: agg function failed [how->mean,dtype->object]

In [40]:
import math

In [53]:
bycomp.mean('sales')

sales
company       
fb       300.0
goog     250.0
tw       600.0

In [42]:
bycomp.sum()

person  sales
company                 
fb       jackrack    600
goog       sammic    500
tw          macmc   1200

In [47]:
bycomp.sum().loc['fb']

person    jackrack
sales          600
Name: fb, dtype: object

In [48]:
bycomp.mean()

TypeError: agg function failed [how->mean,dtype->object]

In [49]:
data={'company':['goog','goog','fb','fb','tw','tw'],
      #'person':['sam','mic','jack','rack','mac','mc'],
      'sales':[200,300,150,450,550,650]}
df2=pd.DataFrame(data)
df2

company  sales
0    goog    200
1    goog    300
2      fb    150
3      fb    450
4      tw    550
5      tw    650

In [50]:
bycomp=df2.groupby('company')

In [51]:
bycomp.mean()

sales
company       
fb       300.0
goog     250.0
tw       600.0

In [52]:
bycomp.sum()

sales
company       
fb         600
goog       500
tw        1200

In [54]:
df2.groupby('company').min()

sales
company       
fb         150
goog       200
tw         550

In [55]:
df2.groupby('company').max()

sales
company       
fb         450
goog       300
tw         650

In [56]:
df2.groupby('company').describe()

sales                                                      
        count   mean         std    min    25%    50%    75%    max
company                                                            
fb        2.0  300.0  212.132034  150.0  225.0  300.0  375.0  450.0
goog      2.0  250.0   70.710678  200.0  225.0  250.0  275.0  300.0
tw        2.0  600.0   70.710678  550.0  575.0  600.0  625.0  650.0

In [57]:
df1=pd.DataFrame({'A':['A0','A1','A2','A3'],
                  'B':['B0','B1','B2','B3'],
                 'C':['C0','C1','C2','C3'],
                 'D':['D0','D1','D2','D3']})
df2=pd.DataFrame({'A':['A4','A5','A6','A7'],
                'B':['B4','B5','B6','B7'],
                 'C':['C4','C5','C6','C7'],
                 'D':['D4','D5','D6','D7']})
df3=pd.DataFrame({'A':['A8','A9','A10','A11'],
                  'B':['B8','B9','B10','B11'],
                 'C':['C8','C9','C10','C11'],
                 'D':['D8','D9','D10','D11']})

In [66]:
df=pd.read_csv('F:\data science\DataSets-main\emp12.csv')
df




1231            Sheethal  9874512510   6/6/1985    Software developer  \
0   1232                Sonu  7458213640   5/5/1995       Software tester   
1   1233             Sandeep  9550025123   3/6/1990    Software architect   
2   1234               Manoj  9254762153   1/7/1990   system adminstrator   
3   1235            Prasanna  9949171267  6/10/1995      software analyst   
4   1236            Priyanka  7095724262   6/8/1995                tester   
5   1237          Shravanthi  9584672135   2/9/1995         Cloud analyst   
6   1238              Yamini  8657215420   2/6/1995            HR Manager   
7   1239           Chaitanya  9125467283   7/4/1994             Architect   
8   1240       Leela Krishna  8542136571   2/3/1994       Software Tester   
9   1241            Mahender  9676521477   4/5/1985             Developer   
10  1242  Yelishetty Shankar  9959243211   4/6/1979               Manager   
11  1243              Swapna  9949343211   2/7/1982  Associate consultant   
12  1244              Nikhil  8019200557   4/8/1994  financial consultant   
13  1245           Sai Kumar  9885662939   4/9/1986            HR Manager   

     25000       Hyderbad     7   No  
0    28000       Madhapur   8.0   No  
1   100000     Gachibowli   7.5   No  
2    65000    Hitech city   8.0   No  
3    15000  Jubliee hills  12.0  Yes  
4    20000  Banjara Hills   9.0   No  
5    28000    Dilsuknagar   7.0   No  
6    19000    Dilsuknagar   8.5   No  
7    25000       Paradise  11.0  Yes  
8    26000   Secunderabad  12.0  Yes  
9    60000           ECIL   7.0   No  
10  100000        LBNagar  13.0  Yes  
11   23000        LBNagar   8.0   No  
12   25000        Tarnaka   8.0   No  
13   30000       Suchitra   9.0   No

In [62]:
df3

A    B    C    D
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [63]:
pd.concat([df1,df2,df3])

A    B    C    D
0   A0   B0   C0   D0
1   A1   B1   C1   D1
2   A2   B2   C2   D2
3   A3   B3   C3   D3
0   A4   B4   C4   D4
1   A5   B5   C5   D5
2   A6   B6   C6   D6
3   A7   B7   C7   D7
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [64]:
pd.concat([df1,df2,df3],axis=1)

A   B   C   D   A   B   C   D    A    B    C    D
0  A0  B0  C0  D0  A4  B4  C4  D4   A8   B8   C8   D8
1  A1  B1  C1  D1  A5  B5  C5  D5   A9   B9   C9   D9
2  A2  B2  C2  D2  A6  B6  C6  D6  A10  B10  C10  D10
3  A3  B3  C3  D3  A7  B7  C7  D7  A11  B11  C11  D11

In [67]:
df=pd.read_csv('F:\data science\DataSets-main\emp12.csv')
df


1231            Sheethal  9874512510   6/6/1985    Software developer  \
0   1232                Sonu  7458213640   5/5/1995       Software tester   
1   1233             Sandeep  9550025123   3/6/1990    Software architect   
2   1234               Manoj  9254762153   1/7/1990   system adminstrator   
3   1235            Prasanna  9949171267  6/10/1995      software analyst   
4   1236            Priyanka  7095724262   6/8/1995                tester   
5   1237          Shravanthi  9584672135   2/9/1995         Cloud analyst   
6   1238              Yamini  8657215420   2/6/1995            HR Manager   
7   1239           Chaitanya  9125467283   7/4/1994             Architect   
8   1240       Leela Krishna  8542136571   2/3/1994       Software Tester   
9   1241            Mahender  9676521477   4/5/1985             Developer   
10  1242  Yelishetty Shankar  9959243211   4/6/1979               Manager   
11  1243              Swapna  9949343211   2/7/1982  Associate consultant   
12  1244              Nikhil  8019200557   4/8/1994  financial consultant   
13  1245           Sai Kumar  9885662939   4/9/1986            HR Manager   

     25000       Hyderbad     7   No  
0    28000       Madhapur   8.0   No  
1   100000     Gachibowli   7.5   No  
2    65000    Hitech city   8.0   No  
3    15000  Jubliee hills  12.0  Yes  
4    20000  Banjara Hills   9.0   No  
5    28000    Dilsuknagar   7.0   No  
6    19000    Dilsuknagar   8.5   No  
7    25000       Paradise  11.0  Yes  
8    26000   Secunderabad  12.0  Yes  
9    60000           ECIL   7.0   No  
10  100000        LBNagar  13.0  Yes  
11   23000        LBNagar   8.0   No  
12   25000        Tarnaka   8.0   No  
13   30000       Suchitra   9.0   No

df.to_csv('text123',index=False)

In [68]:
df.to_csv('text123',index=False) #to write file in csv

In [ ]:
data=pd.read_html('https://www.fdic.gov/bank-failures/failed-bank-list')

In [69]:
data =pd.read_html('https://www.fdic.gov/bank-failures/failed-bank-list')

In [70]:
data

[                               Bank Name               City          State  \
 0     The First National Bank of Lindsay            Lindsay       Oklahoma   
 1  Republic First Bank dba Republic Bank       Philadelphia   Pennsylvania   
 2                          Citizens Bank           Sac City           Iowa   
 3               Heartland Tri-State Bank            Elkhart         Kansas   
 4                    First Republic Bank      San Francisco     California   
 5                         Signature Bank           New York       New York   
 6                    Silicon Valley Bank        Santa Clara     California   
 7                      Almena State Bank             Almena         Kansas   
 8             First City Bank of Florida  Fort Walton Beach        Florida   
 9                   The First State Bank      Barboursville  West Virginia   
 
     Cert                 Aquiring Institution      Closing Date  \
 0   4134   First Bank & Trust Co., Duncan, OK  October 18, 2